version: 2

project_name: flow-cli

builds:
  - id: flow-cli
    main: ./cmd/flow-cli
    binary: flow-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: flowd
    main: ./cmd/flowd
    binary: flowd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: flow-cli
    ids: [flow-cli]
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
  - id: flowd
    ids: [flowd]
    formats: [tar.gz]
    name_template: >-
      flowd_{{ .Version }}_{{ .Os }}_{{ .Arch }}

dockers:
  - id: flowd-amd64
    ids: [flowd]
    goos: linux
    goarch: amd64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --build-arg=VERSION={{.Version}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=MIT
    image_templates:
      - "ghcr.io/krishnakichuu/flowd:{{.Version}}-amd64"
  - id: flowd-arm64
    ids: [flowd]
    goos: linux
    goarch: arm64
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
      - --build-arg=VERSION={{.Version}}
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.licenses=MIT
    image_templates:
      - "ghcr.io/krishnakichuu/flowd:{{.Version}}-arm64"

docker_manifests:
  - name_template: "ghcr.io/krishnakichuu/flowd:{{.Version}}"
    image_templates:
      - "ghcr.io/krishnakichuu/flowd:{{.Version}}-amd64"
      - "ghcr.io/krishnakichuu/flowd:{{.Version}}-arm64"
  - name_template: "ghcr.io/krishnakichuu/flowd:latest"
    image_templates:
      - "ghcr.io/krishnakichuu/flowd:{{.Version}}-amd64"
      - "ghcr.io/krishnakichuu/flowd:{{.Version}}-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: flowd-cli
    ids: [flow-cli]
    repository:
      owner: krishnakichuu
      name: homebrew-flowd
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/krishnakichuu/flowd-engine"
    description: "Operator CLI for flowd, a durable workflow orchestration engine"
    license: "MIT"
    commit_author:
      name: krishna kumar
      email: krishnashaajith@gmail.com
    test: |
      assert_match version.to_s, shell_output("#{bin}/flow-cli version")
    install: |
      bin.install "flow-cli"
