// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeActivityTask = `-- name: CompleteActivityTask :execrows
DELETE FROM activity_tasks
WHERE task_id = $1 AND lease_token = $2
`

type CompleteActivityTaskParams struct {
	TaskID     int64       `json:"task_id"`
	LeaseToken pgtype.UUID `json:"lease_token"`
}

func (q *Queries) CompleteActivityTask(ctx context.Context, arg CompleteActivityTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeActivityTask, arg.TaskID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dequeueActivityTask = `-- name: DequeueActivityTask :one
UPDATE activity_tasks
SET status = 'STARTED',
    lease_token = gen_random_uuid(),
    lease_expiry = now() + make_interval(secs => (start_to_close_timeout_ns::float8 / 1e9))
WHERE task_id = (
    SELECT t.task_id FROM activity_tasks AS t
    WHERE t.task_queue_name = $1
      AND t.namespace_id = $2
      AND t.status = 'PENDING'
      AND t.visible_at <= now()
      AND (
            COALESCE(cardinality($3::int[]), 0) = 0
         OR t.task_queue_partition = ANY($3::int[])
      )
    ORDER BY t.task_id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING task_id, namespace_id, task_queue_name, task_queue_partition, workflow_id, run_id, activity_id, activity_type, scheduled_event_id, input, status, attempt, visible_at, lease_expiry, lease_token, schedule_to_start_timeout_ns, start_to_close_timeout_ns, retry_initial_interval_ns, retry_backoff_coefficient, retry_max_interval_ns, retry_max_attempts, retry_non_retryable_types, created_at
`

type DequeueActivityTaskParams struct {
	TaskQueueName string  `json:"task_queue_name"`
	NamespaceID   int64   `json:"namespace_id"`
	Partitions    []int32 `json:"partitions"`
}

// Lease length is derived from this activity's own start_to_close_timeout,
// not a fixed constant (ADR-0002) — a fixed lease would cause legitimately
// long-running activities to be reaped and double-dispatched.
//
// The partition condition (Phase 2 roadmap, Track C, item 3): an empty (or
// SQL NULL — a nil Go slice binds as NULL, not an empty array) partitions
// array matches every partition, via COALESCE(..., 0) = 0 — a worker that
// never declared which partitions it serves (sdk/worker's default) sees
// everything, exactly as before this feature existed.
func (q *Queries) DequeueActivityTask(ctx context.Context, arg DequeueActivityTaskParams) (ActivityTask, error) {
	row := q.db.QueryRow(ctx, dequeueActivityTask, arg.TaskQueueName, arg.NamespaceID, arg.Partitions)
	var i ActivityTask
	err := row.Scan(
		&i.TaskID,
		&i.NamespaceID,
		&i.TaskQueueName,
		&i.TaskQueuePartition,
		&i.WorkflowID,
		&i.RunID,
		&i.ActivityID,
		&i.ActivityType,
		&i.ScheduledEventID,
		&i.Input,
		&i.Status,
		&i.Attempt,
		&i.VisibleAt,
		&i.LeaseExpiry,
		&i.LeaseToken,
		&i.ScheduleToStartTimeoutNs,
		&i.StartToCloseTimeoutNs,
		&i.RetryInitialIntervalNs,
		&i.RetryBackoffCoefficient,
		&i.RetryMaxIntervalNs,
		&i.RetryMaxAttempts,
		&i.RetryNonRetryableTypes,
		&i.CreatedAt,
	)
	return i, err
}

const enqueueActivityTask = `-- name: EnqueueActivityTask :exec
INSERT INTO activity_tasks (
    namespace_id, task_queue_name, task_queue_partition, workflow_id, run_id, activity_id, activity_type,
    scheduled_event_id, input, status, visible_at,
    schedule_to_start_timeout_ns, start_to_close_timeout_ns,
    retry_initial_interval_ns, retry_backoff_coefficient, retry_max_interval_ns,
    retry_max_attempts, retry_non_retryable_types
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, 'PENDING', now(),
    $10, $11,
    $12, $13, $14,
    $15, $16
)
`

type EnqueueActivityTaskParams struct {
	NamespaceID              int64    `json:"namespace_id"`
	TaskQueueName            string   `json:"task_queue_name"`
	TaskQueuePartition       int32    `json:"task_queue_partition"`
	WorkflowID               string   `json:"workflow_id"`
	RunID                    string   `json:"run_id"`
	ActivityID               int64    `json:"activity_id"`
	ActivityType             string   `json:"activity_type"`
	ScheduledEventID         int64    `json:"scheduled_event_id"`
	Input                    []byte   `json:"input"`
	ScheduleToStartTimeoutNs int64    `json:"schedule_to_start_timeout_ns"`
	StartToCloseTimeoutNs    int64    `json:"start_to_close_timeout_ns"`
	RetryInitialIntervalNs   int64    `json:"retry_initial_interval_ns"`
	RetryBackoffCoefficient  float64  `json:"retry_backoff_coefficient"`
	RetryMaxIntervalNs       int64    `json:"retry_max_interval_ns"`
	RetryMaxAttempts         int32    `json:"retry_max_attempts"`
	RetryNonRetryableTypes   []string `json:"retry_non_retryable_types"`
}

// task_queue_partition is caller-computed (see history.PartitionFor).
func (q *Queries) EnqueueActivityTask(ctx context.Context, arg EnqueueActivityTaskParams) error {
	_, err := q.db.Exec(ctx, enqueueActivityTask,
		arg.NamespaceID,
		arg.TaskQueueName,
		arg.TaskQueuePartition,
		arg.WorkflowID,
		arg.RunID,
		arg.ActivityID,
		arg.ActivityType,
		arg.ScheduledEventID,
		arg.Input,
		arg.ScheduleToStartTimeoutNs,
		arg.StartToCloseTimeoutNs,
		arg.RetryInitialIntervalNs,
		arg.RetryBackoffCoefficient,
		arg.RetryMaxIntervalNs,
		arg.RetryMaxAttempts,
		arg.RetryNonRetryableTypes,
	)
	return err
}

const getActivityTaskByLease = `-- name: GetActivityTaskByLease :one
SELECT task_id, namespace_id, task_queue_name, task_queue_partition, workflow_id, run_id, activity_id, activity_type, scheduled_event_id, input, status, attempt, visible_at, lease_expiry, lease_token, schedule_to_start_timeout_ns, start_to_close_timeout_ns, retry_initial_interval_ns, retry_backoff_coefficient, retry_max_interval_ns, retry_max_attempts, retry_non_retryable_types, created_at FROM activity_tasks WHERE task_id = $1 AND lease_token = $2
`

type GetActivityTaskByLeaseParams struct {
	TaskID     int64       `json:"task_id"`
	LeaseToken pgtype.UUID `json:"lease_token"`
}

// Read the row's full details (input, retry policy, attempt count) before
// CompleteActivityTask/RetryActivityTask consume it, validated against the
// same lease_token so a stale caller sees the same "expired" outcome.
func (q *Queries) GetActivityTaskByLease(ctx context.Context, arg GetActivityTaskByLeaseParams) (ActivityTask, error) {
	row := q.db.QueryRow(ctx, getActivityTaskByLease, arg.TaskID, arg.LeaseToken)
	var i ActivityTask
	err := row.Scan(
		&i.TaskID,
		&i.NamespaceID,
		&i.TaskQueueName,
		&i.TaskQueuePartition,
		&i.WorkflowID,
		&i.RunID,
		&i.ActivityID,
		&i.ActivityType,
		&i.ScheduledEventID,
		&i.Input,
		&i.Status,
		&i.Attempt,
		&i.VisibleAt,
		&i.LeaseExpiry,
		&i.LeaseToken,
		&i.ScheduleToStartTimeoutNs,
		&i.StartToCloseTimeoutNs,
		&i.RetryInitialIntervalNs,
		&i.RetryBackoffCoefficient,
		&i.RetryMaxIntervalNs,
		&i.RetryMaxAttempts,
		&i.RetryNonRetryableTypes,
		&i.CreatedAt,
	)
	return i, err
}

const reapExpiredActivityTasks = `-- name: ReapExpiredActivityTasks :execrows
UPDATE activity_tasks
SET status = 'PENDING', lease_token = NULL, lease_expiry = NULL
WHERE status = 'STARTED' AND lease_expiry < now()
`

func (q *Queries) ReapExpiredActivityTasks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredActivityTasks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryActivityTask = `-- name: RetryActivityTask :execrows
UPDATE activity_tasks
SET status = 'PENDING',
    attempt = attempt + 1,
    visible_at = now() + make_interval(secs => $3::float8),
    lease_token = NULL,
    lease_expiry = NULL
WHERE task_id = $1 AND lease_token = $2
`

type RetryActivityTaskParams struct {
	TaskID         int64       `json:"task_id"`
	LeaseToken     pgtype.UUID `json:"lease_token"`
	BackoffSeconds float64     `json:"backoff_seconds"`
}

// Server-side retry/backoff (ADR-0002): re-queues the task without a new
// history event per attempt, so retries survive worker crashes and history
// stays compact.
func (q *Queries) RetryActivityTask(ctx context.Context, arg RetryActivityTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryActivityTask, arg.TaskID, arg.LeaseToken, arg.BackoffSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
