// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: executions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceNextEventID = `-- name: AdvanceNextEventID :one
UPDATE workflow_executions
SET next_event_id = next_event_id + $1::bigint,
    updated_at = now()
WHERE namespace_id = $2
  AND workflow_id = $3
  AND run_id = $4
  AND next_event_id = $5
RETURNING next_event_id
`

type AdvanceNextEventIDParams struct {
	Increment   int64  `json:"increment"`
	NamespaceID int64  `json:"namespace_id"`
	WorkflowID  string `json:"workflow_id"`
	RunID       string `json:"run_id"`
	Expected    int64  `json:"expected"`
}

// The history-append CAS (ADR-0002, Mechanism B). Returns the new
// next_event_id on success. Zero rows (pgx.ErrNoRows) means a concurrent
// writer already advanced the counter past `expected` — the caller must
// reject the request and discard any in-memory replay state.
func (q *Queries) AdvanceNextEventID(ctx context.Context, arg AdvanceNextEventIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, advanceNextEventID,
		arg.Increment,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.Expected,
	)
	var next_event_id int64
	err := row.Scan(&next_event_id)
	return next_event_id, err
}

const closeWorkflowExecution = `-- name: CloseWorkflowExecution :exec
UPDATE workflow_executions
SET status = $4, close_time = now(), updated_at = now()
WHERE namespace_id = $1 AND workflow_id = $2 AND run_id = $3
`

type CloseWorkflowExecutionParams struct {
	NamespaceID int64  `json:"namespace_id"`
	WorkflowID  string `json:"workflow_id"`
	RunID       string `json:"run_id"`
	Status      string `json:"status"`
}

func (q *Queries) CloseWorkflowExecution(ctx context.Context, arg CloseWorkflowExecutionParams) error {
	_, err := q.db.Exec(ctx, closeWorkflowExecution,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.Status,
	)
	return err
}

const createWorkflowExecution = `-- name: CreateWorkflowExecution :exec
INSERT INTO workflow_executions (
    namespace_id, workflow_id, run_id, workflow_type, task_queue, status,
    next_event_id, shard_id, workflow_execution_timeout_ns, workflow_run_timeout_ns,
    workflow_task_timeout_ns
) VALUES (
    $1, $2, $3, $4, $5, 'RUNNING', 1, $6, $7, $8, $9
)
`

type CreateWorkflowExecutionParams struct {
	NamespaceID                int64       `json:"namespace_id"`
	WorkflowID                 string      `json:"workflow_id"`
	RunID                      string      `json:"run_id"`
	WorkflowType               string      `json:"workflow_type"`
	TaskQueue                  string      `json:"task_queue"`
	ShardID                    int32       `json:"shard_id"`
	WorkflowExecutionTimeoutNs pgtype.Int8 `json:"workflow_execution_timeout_ns"`
	WorkflowRunTimeoutNs       pgtype.Int8 `json:"workflow_run_timeout_ns"`
	WorkflowTaskTimeoutNs      pgtype.Int8 `json:"workflow_task_timeout_ns"`
}

// shard_id is caller-computed (see history.PartitionFor) rather than
// defaulted here: the caller is the one who knows the workflow_id it's
// hashing (ADR-0002 / Phase 2 roadmap, Track C, item 3).
func (q *Queries) CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) error {
	_, err := q.db.Exec(ctx, createWorkflowExecution,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.WorkflowType,
		arg.TaskQueue,
		arg.ShardID,
		arg.WorkflowExecutionTimeoutNs,
		arg.WorkflowRunTimeoutNs,
		arg.WorkflowTaskTimeoutNs,
	)
	return err
}

const getCurrentExecution = `-- name: GetCurrentExecution :one
SELECT namespace_id, workflow_id, run_id, create_request_id FROM current_executions WHERE namespace_id = $1 AND workflow_id = $2
`

type GetCurrentExecutionParams struct {
	NamespaceID int64  `json:"namespace_id"`
	WorkflowID  string `json:"workflow_id"`
}

func (q *Queries) GetCurrentExecution(ctx context.Context, arg GetCurrentExecutionParams) (CurrentExecution, error) {
	row := q.db.QueryRow(ctx, getCurrentExecution, arg.NamespaceID, arg.WorkflowID)
	var i CurrentExecution
	err := row.Scan(
		&i.NamespaceID,
		&i.WorkflowID,
		&i.RunID,
		&i.CreateRequestID,
	)
	return i, err
}

const getWorkflowExecution = `-- name: GetWorkflowExecution :one
SELECT namespace_id, workflow_id, run_id, workflow_type, task_queue, status, next_event_id, shard_id, workflow_execution_timeout_ns, workflow_run_timeout_ns, workflow_task_timeout_ns, start_time, close_time, updated_at, sticky_worker_identity, sticky_expires_at FROM workflow_executions
WHERE namespace_id = $1 AND workflow_id = $2 AND run_id = $3
`

type GetWorkflowExecutionParams struct {
	NamespaceID int64  `json:"namespace_id"`
	WorkflowID  string `json:"workflow_id"`
	RunID       string `json:"run_id"`
}

func (q *Queries) GetWorkflowExecution(ctx context.Context, arg GetWorkflowExecutionParams) (WorkflowExecution, error) {
	row := q.db.QueryRow(ctx, getWorkflowExecution, arg.NamespaceID, arg.WorkflowID, arg.RunID)
	var i WorkflowExecution
	err := row.Scan(
		&i.NamespaceID,
		&i.WorkflowID,
		&i.RunID,
		&i.WorkflowType,
		&i.TaskQueue,
		&i.Status,
		&i.NextEventID,
		&i.ShardID,
		&i.WorkflowExecutionTimeoutNs,
		&i.WorkflowRunTimeoutNs,
		&i.WorkflowTaskTimeoutNs,
		&i.StartTime,
		&i.CloseTime,
		&i.UpdatedAt,
		&i.StickyWorkerIdentity,
		&i.StickyExpiresAt,
	)
	return i, err
}

const insertCurrentExecution = `-- name: InsertCurrentExecution :execrows
INSERT INTO current_executions (namespace_id, workflow_id, run_id, create_request_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (namespace_id, workflow_id) DO NOTHING
`

type InsertCurrentExecutionParams struct {
	NamespaceID     int64  `json:"namespace_id"`
	WorkflowID      string `json:"workflow_id"`
	RunID           string `json:"run_id"`
	CreateRequestID string `json:"create_request_id"`
}

// Idempotency anchor for StartWorkflowExecution: succeeds (1 row) only if no
// run is currently open for this workflow_id.
func (q *Queries) InsertCurrentExecution(ctx context.Context, arg InsertCurrentExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCurrentExecution,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.CreateRequestID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listWorkflowExecutions = `-- name: ListWorkflowExecutions :many
SELECT namespace_id, workflow_id, run_id, workflow_type, task_queue, status, next_event_id, shard_id, workflow_execution_timeout_ns, workflow_run_timeout_ns, workflow_task_timeout_ns, start_time, close_time, updated_at, sticky_worker_identity, sticky_expires_at FROM workflow_executions
WHERE namespace_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR task_queue = $3)
  AND (
        $4::timestamptz IS NULL
        OR (start_time, workflow_id, run_id) < (
          $4::timestamptz,
          $5::text,
          $6::text
        )
      )
ORDER BY start_time DESC, workflow_id DESC, run_id DESC
LIMIT $7
`

type ListWorkflowExecutionsParams struct {
	NamespaceID      int64              `json:"namespace_id"`
	StatusFilter     pgtype.Text        `json:"status_filter"`
	TaskQueue        pgtype.Text        `json:"task_queue"`
	CursorStartTime  pgtype.Timestamptz `json:"cursor_start_time"`
	CursorWorkflowID pgtype.Text        `json:"cursor_workflow_id"`
	CursorRunID      pgtype.Text        `json:"cursor_run_id"`
	PageLimit        int32              `json:"page_limit"`
}

// Keyset-paginated, newest first (Phase 2 roadmap, Track D, item 3: web
// UI). All three ORDER BY columns are DESC specifically so the cursor
// condition below can be a single row-value comparison — start_time alone
// isn't unique, so workflow_id/run_id are tiebreakers, not meaningful
// sort keys on their own. status_filter/task_queue are optional: a NULL
// sqlc.narg matches everything. cursor_start_time NULL means "first
// page" (see idx_workflow_executions_by_start_time, 0004 migration).
func (q *Queries) ListWorkflowExecutions(ctx context.Context, arg ListWorkflowExecutionsParams) ([]WorkflowExecution, error) {
	rows, err := q.db.Query(ctx, listWorkflowExecutions,
		arg.NamespaceID,
		arg.StatusFilter,
		arg.TaskQueue,
		arg.CursorStartTime,
		arg.CursorWorkflowID,
		arg.CursorRunID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowExecution
	for rows.Next() {
		var i WorkflowExecution
		if err := rows.Scan(
			&i.NamespaceID,
			&i.WorkflowID,
			&i.RunID,
			&i.WorkflowType,
			&i.TaskQueue,
			&i.Status,
			&i.NextEventID,
			&i.ShardID,
			&i.WorkflowExecutionTimeoutNs,
			&i.WorkflowRunTimeoutNs,
			&i.WorkflowTaskTimeoutNs,
			&i.StartTime,
			&i.CloseTime,
			&i.UpdatedAt,
			&i.StickyWorkerIdentity,
			&i.StickyExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceCurrentExecution = `-- name: ReplaceCurrentExecution :exec
UPDATE current_executions
SET run_id = $3, create_request_id = $4
WHERE namespace_id = $1 AND workflow_id = $2
`

type ReplaceCurrentExecutionParams struct {
	NamespaceID     int64  `json:"namespace_id"`
	WorkflowID      string `json:"workflow_id"`
	RunID           string `json:"run_id"`
	CreateRequestID string `json:"create_request_id"`
}

// Used when a prior run has closed and a fresh StartWorkflowExecution begins
// a new run for the same workflow_id.
func (q *Queries) ReplaceCurrentExecution(ctx context.Context, arg ReplaceCurrentExecutionParams) error {
	_, err := q.db.Exec(ctx, replaceCurrentExecution,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.CreateRequestID,
	)
	return err
}

const setStickyExecution = `-- name: SetStickyExecution :exec
UPDATE workflow_executions
SET sticky_worker_identity = $4, sticky_expires_at = $5, updated_at = now()
WHERE namespace_id = $1 AND workflow_id = $2 AND run_id = $3
`

type SetStickyExecutionParams struct {
	NamespaceID          int64              `json:"namespace_id"`
	WorkflowID           string             `json:"workflow_id"`
	RunID                string             `json:"run_id"`
	StickyWorkerIdentity pgtype.Text        `json:"sticky_worker_identity"`
	StickyExpiresAt      pgtype.Timestamptz `json:"sticky_expires_at"`
}

// Records (or, with both values NULL, clears) a run's sticky worker
// registration — consulted by every EnqueueWorkflowTask call site to
// decide whether the run's next workflow task should prefer a specific
// worker (see 0002_sticky_workflow_tasks migration).
func (q *Queries) SetStickyExecution(ctx context.Context, arg SetStickyExecutionParams) error {
	_, err := q.db.Exec(ctx, setStickyExecution,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.StickyWorkerIdentity,
		arg.StickyExpiresAt,
	)
	return err
}
