// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package sqlc

import (
	"context"
)

const insertHistoryEvent = `-- name: InsertHistoryEvent :exec
INSERT INTO history_events (namespace_id, workflow_id, run_id, event_id, event_type, attributes)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertHistoryEventParams struct {
	NamespaceID int64  `json:"namespace_id"`
	WorkflowID  string `json:"workflow_id"`
	RunID       string `json:"run_id"`
	EventID     int64  `json:"event_id"`
	EventType   string `json:"event_type"`
	Attributes  []byte `json:"attributes"`
}

func (q *Queries) InsertHistoryEvent(ctx context.Context, arg InsertHistoryEventParams) error {
	_, err := q.db.Exec(ctx, insertHistoryEvent,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.EventID,
		arg.EventType,
		arg.Attributes,
	)
	return err
}

const listHistoryEvents = `-- name: ListHistoryEvents :many
SELECT namespace_id, workflow_id, run_id, event_id, event_time, event_type, attributes FROM history_events
WHERE namespace_id = $1 AND workflow_id = $2 AND run_id = $3
  AND event_id > $4
ORDER BY event_id
LIMIT $5
`

type ListHistoryEventsParams struct {
	NamespaceID  int64  `json:"namespace_id"`
	WorkflowID   string `json:"workflow_id"`
	RunID        string `json:"run_id"`
	AfterEventID int64  `json:"after_event_id"`
	PageLimit    int32  `json:"page_limit"`
}

// Ordered scan on the PK is exactly what the SDK replayer needs: full,
// in-order history from the beginning of the run.
func (q *Queries) ListHistoryEvents(ctx context.Context, arg ListHistoryEventsParams) ([]HistoryEvent, error) {
	rows, err := q.db.Query(ctx, listHistoryEvents,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.AfterEventID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoryEvent
	for rows.Next() {
		var i HistoryEvent
		if err := rows.Scan(
			&i.NamespaceID,
			&i.WorkflowID,
			&i.RunID,
			&i.EventID,
			&i.EventTime,
			&i.EventType,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
