// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityTask struct {
	TaskID                   int64              `json:"task_id"`
	NamespaceID              int64              `json:"namespace_id"`
	TaskQueueName            string             `json:"task_queue_name"`
	TaskQueuePartition       int32              `json:"task_queue_partition"`
	WorkflowID               string             `json:"workflow_id"`
	RunID                    string             `json:"run_id"`
	ActivityID               int64              `json:"activity_id"`
	ActivityType             string             `json:"activity_type"`
	ScheduledEventID         int64              `json:"scheduled_event_id"`
	Input                    []byte             `json:"input"`
	Status                   string             `json:"status"`
	Attempt                  int32              `json:"attempt"`
	VisibleAt                pgtype.Timestamptz `json:"visible_at"`
	LeaseExpiry              pgtype.Timestamptz `json:"lease_expiry"`
	LeaseToken               pgtype.UUID        `json:"lease_token"`
	ScheduleToStartTimeoutNs int64              `json:"schedule_to_start_timeout_ns"`
	StartToCloseTimeoutNs    int64              `json:"start_to_close_timeout_ns"`
	RetryInitialIntervalNs   int64              `json:"retry_initial_interval_ns"`
	RetryBackoffCoefficient  float64            `json:"retry_backoff_coefficient"`
	RetryMaxIntervalNs       int64              `json:"retry_max_interval_ns"`
	RetryMaxAttempts         int32              `json:"retry_max_attempts"`
	RetryNonRetryableTypes   []string           `json:"retry_non_retryable_types"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type CurrentExecution struct {
	NamespaceID     int64  `json:"namespace_id"`
	WorkflowID      string `json:"workflow_id"`
	RunID           string `json:"run_id"`
	CreateRequestID string `json:"create_request_id"`
}

type HistoryEvent struct {
	NamespaceID int64              `json:"namespace_id"`
	WorkflowID  string             `json:"workflow_id"`
	RunID       string             `json:"run_id"`
	EventID     int64              `json:"event_id"`
	EventTime   pgtype.Timestamptz `json:"event_time"`
	EventType   string             `json:"event_type"`
	Attributes  []byte             `json:"attributes"`
}

type Namespace struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QueryTask struct {
	TaskID         int64              `json:"task_id"`
	NamespaceID    int64              `json:"namespace_id"`
	TaskQueueName  string             `json:"task_queue_name"`
	WorkflowID     string             `json:"workflow_id"`
	RunID          string             `json:"run_id"`
	QueryType      string             `json:"query_type"`
	QueryArgs      []byte             `json:"query_args"`
	Status         string             `json:"status"`
	Result         []byte             `json:"result"`
	FailureMessage pgtype.Text        `json:"failure_message"`
	VisibleAt      pgtype.Timestamptz `json:"visible_at"`
	LeaseExpiry    pgtype.Timestamptz `json:"lease_expiry"`
	LeaseToken     pgtype.UUID        `json:"lease_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Timer struct {
	NamespaceID      int64              `json:"namespace_id"`
	WorkflowID       string             `json:"workflow_id"`
	RunID            string             `json:"run_id"`
	TimerID          int64              `json:"timer_id"`
	FireAt           pgtype.Timestamptz `json:"fire_at"`
	ScheduledEventID int64              `json:"scheduled_event_id"`
}

type WorkflowExecution struct {
	NamespaceID                int64              `json:"namespace_id"`
	WorkflowID                 string             `json:"workflow_id"`
	RunID                      string             `json:"run_id"`
	WorkflowType               string             `json:"workflow_type"`
	TaskQueue                  string             `json:"task_queue"`
	Status                     string             `json:"status"`
	NextEventID                int64              `json:"next_event_id"`
	ShardID                    int32              `json:"shard_id"`
	WorkflowExecutionTimeoutNs pgtype.Int8        `json:"workflow_execution_timeout_ns"`
	WorkflowRunTimeoutNs       pgtype.Int8        `json:"workflow_run_timeout_ns"`
	WorkflowTaskTimeoutNs      pgtype.Int8        `json:"workflow_task_timeout_ns"`
	StartTime                  pgtype.Timestamptz `json:"start_time"`
	CloseTime                  pgtype.Timestamptz `json:"close_time"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	StickyWorkerIdentity       pgtype.Text        `json:"sticky_worker_identity"`
	StickyExpiresAt            pgtype.Timestamptz `json:"sticky_expires_at"`
}

type WorkflowTask struct {
	TaskID                  int64              `json:"task_id"`
	NamespaceID             int64              `json:"namespace_id"`
	TaskQueueName           string             `json:"task_queue_name"`
	TaskQueuePartition      int32              `json:"task_queue_partition"`
	WorkflowID              string             `json:"workflow_id"`
	RunID                   string             `json:"run_id"`
	ScheduledEventID        int64              `json:"scheduled_event_id"`
	Status                  string             `json:"status"`
	VisibleAt               pgtype.Timestamptz `json:"visible_at"`
	LeaseExpiry             pgtype.Timestamptz `json:"lease_expiry"`
	LeaseToken              pgtype.UUID        `json:"lease_token"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PreferredWorkerIdentity pgtype.Text        `json:"preferred_worker_identity"`
	StickyDeadline          pgtype.Timestamptz `json:"sticky_deadline"`
}
