// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: namespaces.sql

package sqlc

import (
	"context"
)

const createNamespace = `-- name: CreateNamespace :one
INSERT INTO namespaces (name) VALUES ($1)
ON CONFLICT (name) DO NOTHING
RETURNING id, name, created_at
`

func (q *Queries) CreateNamespace(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRow(ctx, createNamespace, name)
	var i Namespace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getNamespaceByName = `-- name: GetNamespaceByName :one
SELECT id, name, created_at FROM namespaces WHERE name = $1
`

func (q *Queries) GetNamespaceByName(ctx context.Context, name string) (Namespace, error) {
	row := q.db.QueryRow(ctx, getNamespaceByName, name)
	var i Namespace
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, name, created_at FROM namespaces ORDER BY name
`

func (q *Queries) ListNamespaces(ctx context.Context) ([]Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
