// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	// The history-append CAS (ADR-0002, Mechanism B). Returns the new
	// next_event_id on success. Zero rows (pgx.ErrNoRows) means a concurrent
	// writer already advanced the counter past `expected` — the caller must
	// reject the request and discard any in-memory replay state.
	AdvanceNextEventID(ctx context.Context, arg AdvanceNextEventIDParams) (int64, error)
	CloseWorkflowExecution(ctx context.Context, arg CloseWorkflowExecutionParams) error
	CompleteActivityTask(ctx context.Context, arg CompleteActivityTaskParams) (int64, error)
	// Unlike CompleteWorkflowTask/CompleteActivityTask, this doesn't delete
	// the row — the result has to stay readable until QueryWorkflowExecution's
	// own polling loop reads it and deletes it itself (see DeleteQueryTask).
	CompleteQueryTask(ctx context.Context, arg CompleteQueryTaskParams) (int64, error)
	// Deletes the task row only if the caller's lease_token still matches,
	// rejecting stale completions from a worker whose lease already expired
	// and was reassigned.
	CompleteWorkflowTask(ctx context.Context, arg CompleteWorkflowTaskParams) (int64, error)
	CreateNamespace(ctx context.Context, name string) (Namespace, error)
	// shard_id is caller-computed (see history.PartitionFor) rather than
	// defaulted here: the caller is the one who knows the workflow_id it's
	// hashing (ADR-0002 / Phase 2 roadmap, Track C, item 3).
	CreateWorkflowExecution(ctx context.Context, arg CreateWorkflowExecutionParams) error
	DeleteQueryTask(ctx context.Context, taskID int64) error
	// Lease length is derived from this activity's own start_to_close_timeout,
	// not a fixed constant (ADR-0002) — a fixed lease would cause legitimately
	// long-running activities to be reaped and double-dispatched.
	//
	// The partition condition (Phase 2 roadmap, Track C, item 3): an empty (or
	// SQL NULL — a nil Go slice binds as NULL, not an empty array) partitions
	// array matches every partition, via COALESCE(..., 0) = 0 — a worker that
	// never declared which partitions it serves (sdk/worker's default) sees
	// everything, exactly as before this feature existed.
	DequeueActivityTask(ctx context.Context, arg DequeueActivityTaskParams) (ActivityTask, error)
	// Same FOR UPDATE SKIP LOCKED pattern as task dispatch: lets multiple server
	// instances run the timer-firing scan concurrently without double-firing.
	DequeueDueTimer(ctx context.Context) (Timer, error)
	// Same FOR UPDATE SKIP LOCKED dispatch as workflow/activity tasks
	// (ADR-0002, Mechanism A).
	DequeueQueryTask(ctx context.Context, arg DequeueQueryTaskParams) (QueryTask, error)
	// ADR-0002, Mechanism A. FOR UPDATE SKIP LOCKED gives exactly-one-winner
	// semantics across concurrently polling workers without blocking on
	// contended rows. Zero rows (pgx.ErrNoRows) means no task is currently
	// available for this queue.
	//
	// The sticky condition: a row with a preferred_worker_identity is invisible
	// to every other worker until either that worker asks (worker_identity
	// matches) or sticky_deadline passes, at which point it's fair game for
	// anyone — the fallback-to-full-replay path sticky caching depends on,
	// using the same table and the same SKIP LOCKED dispatch as always.
	//
	// The partition condition (Phase 2 roadmap, Track C, item 3): an empty (or
	// SQL NULL — a nil Go slice binds as NULL, not an empty array) partitions
	// array matches every partition, via COALESCE(..., 0) = 0 — a worker that
	// never declared which partitions it serves (sdk/worker's default) sees
	// everything, exactly as before this feature existed.
	DequeueWorkflowTask(ctx context.Context, arg DequeueWorkflowTaskParams) (WorkflowTask, error)
	// task_queue_partition is caller-computed (see history.PartitionFor).
	EnqueueActivityTask(ctx context.Context, arg EnqueueActivityTaskParams) error
	EnqueueQueryTask(ctx context.Context, arg EnqueueQueryTaskParams) (QueryTask, error)
	// preferred_worker_identity/sticky_deadline are NULL for a normal
	// (non-sticky) enqueue — every existing caller before sticky caching
	// passed the equivalent of "no preference," and still does explicitly.
	// task_queue_partition is caller-computed (see history.PartitionFor).
	EnqueueWorkflowTask(ctx context.Context, arg EnqueueWorkflowTaskParams) error
	FailQueryTask(ctx context.Context, arg FailQueryTaskParams) (int64, error)
	// Read the row's full details (input, retry policy, attempt count) before
	// CompleteActivityTask/RetryActivityTask consume it, validated against the
	// same lease_token so a stale caller sees the same "expired" outcome.
	GetActivityTaskByLease(ctx context.Context, arg GetActivityTaskByLeaseParams) (ActivityTask, error)
	GetCurrentExecution(ctx context.Context, arg GetCurrentExecutionParams) (CurrentExecution, error)
	GetNamespaceByName(ctx context.Context, name string) (Namespace, error)
	GetQueryTask(ctx context.Context, arg GetQueryTaskParams) (QueryTask, error)
	GetWorkflowExecution(ctx context.Context, arg GetWorkflowExecutionParams) (WorkflowExecution, error)
	// Idempotency anchor for StartWorkflowExecution: succeeds (1 row) only if no
	// run is currently open for this workflow_id.
	InsertCurrentExecution(ctx context.Context, arg InsertCurrentExecutionParams) (int64, error)
	InsertHistoryEvent(ctx context.Context, arg InsertHistoryEventParams) error
	InsertTimer(ctx context.Context, arg InsertTimerParams) error
	// Ordered scan on the PK is exactly what the SDK replayer needs: full,
	// in-order history from the beginning of the run.
	ListHistoryEvents(ctx context.Context, arg ListHistoryEventsParams) ([]HistoryEvent, error)
	ListNamespaces(ctx context.Context) ([]Namespace, error)
	// Keyset-paginated, newest first (Phase 2 roadmap, Track D, item 3: web
	// UI). All three ORDER BY columns are DESC specifically so the cursor
	// condition below can be a single row-value comparison — start_time alone
	// isn't unique, so workflow_id/run_id are tiebreakers, not meaningful
	// sort keys on their own. status_filter/task_queue are optional: a NULL
	// sqlc.narg matches everything. cursor_start_time NULL means "first
	// page" (see idx_workflow_executions_by_start_time, 0004 migration).
	ListWorkflowExecutions(ctx context.Context, arg ListWorkflowExecutionsParams) ([]WorkflowExecution, error)
	ReapExpiredActivityTasks(ctx context.Context) (int64, error)
	ReapExpiredQueryTasks(ctx context.Context) (int64, error)
	// Background lease reaper: resets tasks whose worker crashed after
	// acquiring the lease but before responding, back to PENDING for
	// redispatch.
	ReapExpiredWorkflowTasks(ctx context.Context) (int64, error)
	// Used when a prior run has closed and a fresh StartWorkflowExecution begins
	// a new run for the same workflow_id.
	ReplaceCurrentExecution(ctx context.Context, arg ReplaceCurrentExecutionParams) error
	// Server-side retry/backoff (ADR-0002): re-queues the task without a new
	// history event per attempt, so retries survive worker crashes and history
	// stays compact.
	RetryActivityTask(ctx context.Context, arg RetryActivityTaskParams) (int64, error)
	// Records (or, with both values NULL, clears) a run's sticky worker
	// registration — consulted by every EnqueueWorkflowTask call site to
	// decide whether the run's next workflow task should prefer a specific
	// worker (see 0002_sticky_workflow_tasks migration).
	SetStickyExecution(ctx context.Context, arg SetStickyExecutionParams) error
}

var _ Querier = (*Queries)(nil)
