// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeQueryTask = `-- name: CompleteQueryTask :execrows
UPDATE query_tasks
SET status = 'COMPLETED', result = $3
WHERE task_id = $1 AND lease_token = $2
`

type CompleteQueryTaskParams struct {
	TaskID     int64       `json:"task_id"`
	LeaseToken pgtype.UUID `json:"lease_token"`
	Result     []byte      `json:"result"`
}

// Unlike CompleteWorkflowTask/CompleteActivityTask, this doesn't delete
// the row — the result has to stay readable until QueryWorkflowExecution's
// own polling loop reads it and deletes it itself (see DeleteQueryTask).
func (q *Queries) CompleteQueryTask(ctx context.Context, arg CompleteQueryTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeQueryTask, arg.TaskID, arg.LeaseToken, arg.Result)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteQueryTask = `-- name: DeleteQueryTask :exec
DELETE FROM query_tasks WHERE task_id = $1
`

func (q *Queries) DeleteQueryTask(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteQueryTask, taskID)
	return err
}

const dequeueQueryTask = `-- name: DequeueQueryTask :one
UPDATE query_tasks
SET status = 'STARTED',
    lease_token = gen_random_uuid(),
    lease_expiry = now() + make_interval(secs => $1::float8)
WHERE task_id = (
    SELECT t.task_id FROM query_tasks AS t
    WHERE t.task_queue_name = $2
      AND t.namespace_id = $3
      AND t.status = 'PENDING'
      AND t.visible_at <= now()
    ORDER BY t.task_id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING task_id, namespace_id, task_queue_name, workflow_id, run_id, query_type, query_args, status, result, failure_message, visible_at, lease_expiry, lease_token, created_at
`

type DequeueQueryTaskParams struct {
	LeaseSeconds  float64 `json:"lease_seconds"`
	TaskQueueName string  `json:"task_queue_name"`
	NamespaceID   int64   `json:"namespace_id"`
}

// Same FOR UPDATE SKIP LOCKED dispatch as workflow/activity tasks
// (ADR-0002, Mechanism A).
func (q *Queries) DequeueQueryTask(ctx context.Context, arg DequeueQueryTaskParams) (QueryTask, error) {
	row := q.db.QueryRow(ctx, dequeueQueryTask, arg.LeaseSeconds, arg.TaskQueueName, arg.NamespaceID)
	var i QueryTask
	err := row.Scan(
		&i.TaskID,
		&i.NamespaceID,
		&i.TaskQueueName,
		&i.WorkflowID,
		&i.RunID,
		&i.QueryType,
		&i.QueryArgs,
		&i.Status,
		&i.Result,
		&i.FailureMessage,
		&i.VisibleAt,
		&i.LeaseExpiry,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}

const enqueueQueryTask = `-- name: EnqueueQueryTask :one
INSERT INTO query_tasks (namespace_id, task_queue_name, workflow_id, run_id, query_type, query_args, status, visible_at)
VALUES ($1, $2, $3, $4, $5, $6, 'PENDING', now())
RETURNING task_id, namespace_id, task_queue_name, workflow_id, run_id, query_type, query_args, status, result, failure_message, visible_at, lease_expiry, lease_token, created_at
`

type EnqueueQueryTaskParams struct {
	NamespaceID   int64  `json:"namespace_id"`
	TaskQueueName string `json:"task_queue_name"`
	WorkflowID    string `json:"workflow_id"`
	RunID         string `json:"run_id"`
	QueryType     string `json:"query_type"`
	QueryArgs     []byte `json:"query_args"`
}

func (q *Queries) EnqueueQueryTask(ctx context.Context, arg EnqueueQueryTaskParams) (QueryTask, error) {
	row := q.db.QueryRow(ctx, enqueueQueryTask,
		arg.NamespaceID,
		arg.TaskQueueName,
		arg.WorkflowID,
		arg.RunID,
		arg.QueryType,
		arg.QueryArgs,
	)
	var i QueryTask
	err := row.Scan(
		&i.TaskID,
		&i.NamespaceID,
		&i.TaskQueueName,
		&i.WorkflowID,
		&i.RunID,
		&i.QueryType,
		&i.QueryArgs,
		&i.Status,
		&i.Result,
		&i.FailureMessage,
		&i.VisibleAt,
		&i.LeaseExpiry,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}

const failQueryTask = `-- name: FailQueryTask :execrows
UPDATE query_tasks
SET status = 'FAILED', failure_message = $3
WHERE task_id = $1 AND lease_token = $2
`

type FailQueryTaskParams struct {
	TaskID         int64       `json:"task_id"`
	LeaseToken     pgtype.UUID `json:"lease_token"`
	FailureMessage pgtype.Text `json:"failure_message"`
}

func (q *Queries) FailQueryTask(ctx context.Context, arg FailQueryTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, failQueryTask, arg.TaskID, arg.LeaseToken, arg.FailureMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getQueryTask = `-- name: GetQueryTask :one
SELECT task_id, namespace_id, task_queue_name, workflow_id, run_id, query_type, query_args, status, result, failure_message, visible_at, lease_expiry, lease_token, created_at FROM query_tasks WHERE task_id = $1 AND namespace_id = $2
`

type GetQueryTaskParams struct {
	TaskID      int64 `json:"task_id"`
	NamespaceID int64 `json:"namespace_id"`
}

func (q *Queries) GetQueryTask(ctx context.Context, arg GetQueryTaskParams) (QueryTask, error) {
	row := q.db.QueryRow(ctx, getQueryTask, arg.TaskID, arg.NamespaceID)
	var i QueryTask
	err := row.Scan(
		&i.TaskID,
		&i.NamespaceID,
		&i.TaskQueueName,
		&i.WorkflowID,
		&i.RunID,
		&i.QueryType,
		&i.QueryArgs,
		&i.Status,
		&i.Result,
		&i.FailureMessage,
		&i.VisibleAt,
		&i.LeaseExpiry,
		&i.LeaseToken,
		&i.CreatedAt,
	)
	return i, err
}

const reapExpiredQueryTasks = `-- name: ReapExpiredQueryTasks :execrows
UPDATE query_tasks
SET status = 'PENDING', lease_token = NULL, lease_expiry = NULL
WHERE status = 'STARTED' AND lease_expiry < now()
`

func (q *Queries) ReapExpiredQueryTasks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredQueryTasks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
