// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dequeueDueTimer = `-- name: DequeueDueTimer :one
DELETE FROM timers
WHERE (namespace_id, workflow_id, run_id, timer_id) = (
    SELECT t.namespace_id, t.workflow_id, t.run_id, t.timer_id FROM timers AS t
    WHERE t.fire_at <= now()
    ORDER BY t.fire_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING namespace_id, workflow_id, run_id, timer_id, fire_at, scheduled_event_id
`

// Same FOR UPDATE SKIP LOCKED pattern as task dispatch: lets multiple server
// instances run the timer-firing scan concurrently without double-firing.
func (q *Queries) DequeueDueTimer(ctx context.Context) (Timer, error) {
	row := q.db.QueryRow(ctx, dequeueDueTimer)
	var i Timer
	err := row.Scan(
		&i.NamespaceID,
		&i.WorkflowID,
		&i.RunID,
		&i.TimerID,
		&i.FireAt,
		&i.ScheduledEventID,
	)
	return i, err
}

const insertTimer = `-- name: InsertTimer :exec
INSERT INTO timers (namespace_id, workflow_id, run_id, timer_id, fire_at, scheduled_event_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTimerParams struct {
	NamespaceID      int64              `json:"namespace_id"`
	WorkflowID       string             `json:"workflow_id"`
	RunID            string             `json:"run_id"`
	TimerID          int64              `json:"timer_id"`
	FireAt           pgtype.Timestamptz `json:"fire_at"`
	ScheduledEventID int64              `json:"scheduled_event_id"`
}

func (q *Queries) InsertTimer(ctx context.Context, arg InsertTimerParams) error {
	_, err := q.db.Exec(ctx, insertTimer,
		arg.NamespaceID,
		arg.WorkflowID,
		arg.RunID,
		arg.TimerID,
		arg.FireAt,
		arg.ScheduledEventID,
	)
	return err
}
