// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow_tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeWorkflowTask = `-- name: CompleteWorkflowTask :execrows
DELETE FROM workflow_tasks
WHERE task_id = $1 AND lease_token = $2
`

type CompleteWorkflowTaskParams struct {
	TaskID     int64       `json:"task_id"`
	LeaseToken pgtype.UUID `json:"lease_token"`
}

// Deletes the task row only if the caller's lease_token still matches,
// rejecting stale completions from a worker whose lease already expired
// and was reassigned.
func (q *Queries) CompleteWorkflowTask(ctx context.Context, arg CompleteWorkflowTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeWorkflowTask, arg.TaskID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dequeueWorkflowTask = `-- name: DequeueWorkflowTask :one
UPDATE workflow_tasks
SET status = 'STARTED',
    lease_token = gen_random_uuid(),
    lease_expiry = now() + make_interval(secs => $1::float8)
WHERE task_id = (
    SELECT t.task_id FROM workflow_tasks AS t
    WHERE t.task_queue_name = $2
      AND t.namespace_id = $3
      AND t.status = 'PENDING'
      AND t.visible_at <= now()
      AND (
            t.preferred_worker_identity IS NULL
         OR t.preferred_worker_identity = $4
         OR t.sticky_deadline < now()
      )
      AND (
            COALESCE(cardinality($5::int[]), 0) = 0
         OR t.task_queue_partition = ANY($5::int[])
      )
    ORDER BY t.task_id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING task_id, namespace_id, task_queue_name, task_queue_partition, workflow_id, run_id, scheduled_event_id, status, visible_at, lease_expiry, lease_token, created_at, preferred_worker_identity, sticky_deadline
`

type DequeueWorkflowTaskParams struct {
	LeaseSeconds   float64     `json:"lease_seconds"`
	TaskQueueName  string      `json:"task_queue_name"`
	NamespaceID    int64       `json:"namespace_id"`
	WorkerIdentity pgtype.Text `json:"worker_identity"`
	Partitions     []int32     `json:"partitions"`
}

// ADR-0002, Mechanism A. FOR UPDATE SKIP LOCKED gives exactly-one-winner
// semantics across concurrently polling workers without blocking on
// contended rows. Zero rows (pgx.ErrNoRows) means no task is currently
// available for this queue.
//
// The sticky condition: a row with a preferred_worker_identity is invisible
// to every other worker until either that worker asks (worker_identity
// matches) or sticky_deadline passes, at which point it's fair game for
// anyone — the fallback-to-full-replay path sticky caching depends on,
// using the same table and the same SKIP LOCKED dispatch as always.
//
// The partition condition (Phase 2 roadmap, Track C, item 3): an empty (or
// SQL NULL — a nil Go slice binds as NULL, not an empty array) partitions
// array matches every partition, via COALESCE(..., 0) = 0 — a worker that
// never declared which partitions it serves (sdk/worker's default) sees
// everything, exactly as before this feature existed.
func (q *Queries) DequeueWorkflowTask(ctx context.Context, arg DequeueWorkflowTaskParams) (WorkflowTask, error) {
	row := q.db.QueryRow(ctx, dequeueWorkflowTask,
		arg.LeaseSeconds,
		arg.TaskQueueName,
		arg.NamespaceID,
		arg.WorkerIdentity,
		arg.Partitions,
	)
	var i WorkflowTask
	err := row.Scan(
		&i.TaskID,
		&i.NamespaceID,
		&i.TaskQueueName,
		&i.TaskQueuePartition,
		&i.WorkflowID,
		&i.RunID,
		&i.ScheduledEventID,
		&i.Status,
		&i.VisibleAt,
		&i.LeaseExpiry,
		&i.LeaseToken,
		&i.CreatedAt,
		&i.PreferredWorkerIdentity,
		&i.StickyDeadline,
	)
	return i, err
}

const enqueueWorkflowTask = `-- name: EnqueueWorkflowTask :exec
INSERT INTO workflow_tasks (
    namespace_id, task_queue_name, task_queue_partition, workflow_id, run_id, scheduled_event_id,
    status, visible_at, preferred_worker_identity, sticky_deadline
)
VALUES ($1, $2, $3, $4, $5, $6, 'PENDING', now(), $7, $8)
`

type EnqueueWorkflowTaskParams struct {
	NamespaceID             int64              `json:"namespace_id"`
	TaskQueueName           string             `json:"task_queue_name"`
	TaskQueuePartition      int32              `json:"task_queue_partition"`
	WorkflowID              string             `json:"workflow_id"`
	RunID                   string             `json:"run_id"`
	ScheduledEventID        int64              `json:"scheduled_event_id"`
	PreferredWorkerIdentity pgtype.Text        `json:"preferred_worker_identity"`
	StickyDeadline          pgtype.Timestamptz `json:"sticky_deadline"`
}

// preferred_worker_identity/sticky_deadline are NULL for a normal
// (non-sticky) enqueue — every existing caller before sticky caching
// passed the equivalent of "no preference," and still does explicitly.
// task_queue_partition is caller-computed (see history.PartitionFor).
func (q *Queries) EnqueueWorkflowTask(ctx context.Context, arg EnqueueWorkflowTaskParams) error {
	_, err := q.db.Exec(ctx, enqueueWorkflowTask,
		arg.NamespaceID,
		arg.TaskQueueName,
		arg.TaskQueuePartition,
		arg.WorkflowID,
		arg.RunID,
		arg.ScheduledEventID,
		arg.PreferredWorkerIdentity,
		arg.StickyDeadline,
	)
	return err
}

const reapExpiredWorkflowTasks = `-- name: ReapExpiredWorkflowTasks :execrows
UPDATE workflow_tasks
SET status = 'PENDING', lease_token = NULL, lease_expiry = NULL
WHERE status = 'STARTED' AND lease_expiry < now()
`

// Background lease reaper: resets tasks whose worker crashed after
// acquiring the lease but before responding, back to PENDING for
// redispatch.
func (q *Queries) ReapExpiredWorkflowTasks(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredWorkflowTasks)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
